<?php

namespace App\Repositories;

use App\Models\Genre;
use Illuminate\Support\Facades\DB;

class GenreRepository extends EloquentRepository
{

    public function getModel()
    {
        return Genre::class;
    }

    public function getGenreByTitle($title) {
        return DB::table('tbl_genre')
            ->where('title', 'like', '%'.$title.'%')
            ->first();
    }

    public function maxPosition() {
        return DB::table('tbl_genre')->max('position');
    }

    public function getAll()
    {
        return Genre::all()->sortBy('position'); // TODO: Change the autogenerated stub
    }
}
