<?php

namespace App\Repositories;

use App\Models\Genre;
use App\Models\Pack;
use Illuminate\Support\Facades\DB;

class PackRepository extends EloquentRepository
{

    public function getModel()
    {
        return Pack::class;
    }

    public function getPackByTitle($title) {
        return DB::table('tbl_pack')
            ->where('title', 'like', '%'.$title.'%')
            ->first();
    }

    public function maxPosition() {
        return DB::table('tbl_pack')->max('position');
    }

    public function getAll()
    {
        return Pack::all()->sortBy('position'); // TODO: Change the autogenerated stub
    }
}
