<?php

namespace App\Repositories;

use App\Models\Poster;
use App\Models\Role;
use Illuminate\Support\Facades\DB;

class RoleRepository extends EloquentRepository
{
    public function getModel()
    {
        return Role::class;
    }

    public function maxPosition($poster_id) {
        return DB::table('tbl_role')->where('poster_id', '=' , $poster_id)->max('position');
    }

    public function getAll()
    {
        return Role::all()->sortBy('position'); // TODO: Change the autogenerated stub
    }

    public function getByPosterId($id)
    {
        return DB::table('tbl_role')->where('poster_id', '=', $id)->orderBy('position', 'asc')->get();
    }
}
