<?php

namespace App\Repositories;

use App\Models\Genre;
use App\Models\Season;
use Illuminate\Support\Facades\DB;

class SeasonRepository extends EloquentRepository
{

    public function getModel()
    {
        return Season::class;
    }

    public function getSeasonByTitle($title) {
        return DB::table('tbl_season')
            ->where('title', 'like', '%'.$title.'%')
            ->first();
    }

    public function maxPosition() {
        return DB::table('tbl_season')->max('position');
    }

    public function getAll()
    {
        return Season::all()->sortBy('position'); // TODO: Change the autogenerated stub
    }
}
