<?php

namespace App\Repositories;

use App\Models\Genre;
use App\Models\Season;
use Illuminate\Support\Facades\DB;

class SeasonRepository extends EloquentRepository
{

    public function getModel()
    {
        return Season::class;
    }

    public function getSeasonByTitle($title) {
        return DB::table('tbl_season')
            ->where('title', 'like', '%'.$title.'%')
            ->first();
    }

    public function maxPosition($id) {
        return DB::table('tbl_season')->where('poster_id', '=', $id)->max('position');
    }

    public function getAllSeason($tvshowId)
    {
        return Season::all()->where('poster_id', '=', $tvshowId)->sortBy('position'); // TODO: Change the autogenerated stub
    }

    public function getSeasons($id) {
        return DB::table('tbl_season')->where('poster_id', '=', $id)->orderBy('position')->get();
    }
}
