<?php

namespace App\Repositories;

use App\Models\Subscription;
use Illuminate\Support\Facades\DB;

class SubscriptionRepository extends EloquentRepository
{

    public function getModel()
    {
        return Subscription::class;
    }

    public function getAll()
    {
        return Subscription::orderByDesc('id')->get(); // TODO: Change the autogenerated stub
    }

    public function getLastSubByUserId($id)
    {
        return Subscription::where('user_id', $id)->orderByDesc('created_at', 'desc')->first();
    }

    public function totalEarning()
    {
        return DB::table('tbl_subscription')->where('status', 'like', '%COMPLETED%')->sum('price');
    }

    public function getRecent(int $limit)
    {
        return DB::table('tbl_subscription')->where('status', 'like' ,'COMPLETED')->orderBy('id', 'desc')->take($limit)->get();
    }
}
