<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//        DB::table('tbl_poster')->insert([
//            'title' => 'The Peripheral (2022)',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 6.7,
//            'year' => 2022,
//            'description' => 'Stuck in a small Appalachian town, a young woman’s only escape from the daily grind is playing advanced video games. She is such a good player that a company sends her a new video game system to test…but it has a surprise in store. It unlocks all of her dreams of finding a purpose, romance, and glamour in what seems like a game…but it also puts her and her family in real danger.',
//            'label' => 'The Peripheral (2022)',
//            'subLabel' => 'The Peripheral (2022)',
//            'slug' => Str::slug('The Peripheral (2022)'),
//            'comment' => 0,
//            'enable' => 1,
//          ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Chainsaw Man (2022)',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2022,
//            'description' => 'Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.',
//            'label' => 'Chainsaw Man (2022)',
//            'subLabel' => 'Chainsaw Man (2022)',
//            'slug' => Str::slug('Chainsaw Man (2022)'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Black Adam',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 7.9,
//            'year' => 2022,
//            'description' => 'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
//            'label' => 'Black Adam',
//            'subLabel' => 'Black Adam',
//            'slug' => Str::slug('Black Adam'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Fall',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2022,
//            'description' => 'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights',
//            'label' => 'Fall',
//            'subLabel' => 'Fall',
//            'slug' => Str::slug('Fall'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Coco',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2017,
//            'description' => 'Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel\'s family history.',
//            'label' => 'Coco',
//            'subLabel' => 'Coco',
//            'slug' => Str::slug('Coco'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Hocus Pocus 2',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2022,
//            'description' => '29 years since the Black Flame Candle was last lit, the 17th-century Sanderson sisters are resurrected, and they are looking for revenge. Now it\'s up to three high school students to stop the ravenous witches from wreaking a new kind of havoc on Salem before dawn on All Hallow\'s Eve.',
//            'label' => 'Hocus Pocus 2',
//            'subLabel' => 'Hocus Pocus 2',
//            'slug' => Str::slug('Hocus Pocus 2'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Project Gemini',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2022,
//            'description' => 'After depleting Earth\'s resources for centuries, humankind\'s survival requires an exodus to outer space. An international expedition is quickly formed to find a suitable new planet, but when plans go awry, the crew is suddenly stranded without power on a strange planet, where something unimaginable lies in wait.',
//            'label' => 'Project Gemini',
//            'subLabel' => 'Project Gemini',
//            'slug' => Str::slug('Project Gemini'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Orphan: First Kill',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2022,
//            'description' => 'After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.',
//            'label' => 'Orphan: First Kill',
//            'subLabel' => 'Orphan: First Kill',
//            'slug' => Str::slug('Orphan: First Kill'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Mirai',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2018,
//            'description' => 'Unhappy after his new baby sister displaces him, four-year-old Kun begins meeting people and pets from his family\'s history in their unique house in order to help him become the big brother he was meant to be.',
//            'label' => 'Mirai',
//            'subLabel' => 'Mirai',
//            'slug' => Str::slug('Mirai'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'The Boy and the Beast',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2015,
//            'description' => 'Kyuta, a boy living in Shibuya, and Kumatetsu, a lonesome beast from Jutengai, an imaginary world. One day, Kyuta forays into the imaginary world and, as he\'s looking for his way back, meets Kumatetsu who becomes his spirit guide. That encounter leads them to many adventures.',
//            'label' => 'The Boy and the Beast',
//            'subLabel' => 'The Boy and the Beast',
//            'slug' => Str::slug('The Boy and the Beast'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Flutter',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2017,
//            'description' => 'In a world, where every living creature can defy gravity and fly at will, being stuck on the ground is no fun. If all you can manage is to trudge along, loneliness, depression and despair come knocking on your door. Letting them come in is an option. Finding the courage to soar is priceless.',
//            'label' => 'Flutter',
//            'subLabel' => 'Flutter',
//            'slug' => Str::slug('Flutter'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Samaritan',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 7.0,
//            'year' => 2022,
//            'description' => 'Thirteen year old Sam Cleary suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.',
//            'label' => 'Samaritan',
//            'subLabel' => 'Samaritan',
//            'slug' => Str::slug('Samaritan'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Lou',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2022,
//            'description' => 'A young girl is kidnapped during a powerful storm. Her mother joins forces with her mysterious neighbour to set off in pursuit of the kidnapper. Their journey will test their limits and expose the dark secrets of their past.',
//            'label' => 'Lou',
//            'subLabel' => 'Lou',
//            'slug' => Str::slug('Lou'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Don\'t Worry Darling',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.0,
//            'year' => 2022,
//            'description' => 'Alice and Jack are lucky to be living in the idealized community of Victory, the experimental company town housing the men who work for the top-secret Victory Project and their families. But when cracks in their idyllic life begin to appear, exposing flashes of something much more sinister lurking beneath the attractive façade, Alice can’t help questioning exactly what they’re doing in Victory, and why.',
//            'label' => 'Don\'t Worry Darling',
//            'subLabel' => 'Don\'t Worry Darling',
//            'slug' => Str::slug('Don\'t Worry Darling'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => '20th Century Girl',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 7.6,
//            'year' => 2022,
//            'description' => 'Yeon-du asks her best friend Bora to collect all the information she can about Baek Hyun-jin while she is away in the U.S. for heart surgery. Bora decides to get close to Baek\'s best friend, Pung Woon-ho first. However, Bora\'s clumsy plan unfolds in an unexpected direction. In 1999, a year before the new century, Bora, who turns seventeen, falls into the fever of first love.',
//            'label' => '20th Century Girl',
//            'subLabel' => '20th Century Girl',
//            'slug' => Str::slug('20th Century Girl'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'The Woman King',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 7.8,
//            'year' => 2022,
//            'description' => 'The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.',
//            'label' => 'The Woman King',
//            'subLabel' => 'The Woman King',
//            'slug' => Str::slug('The Woman King'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Wild Is the Wind',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 7.4,
//            'year' => 2022,
//            'description' => 'When two corrupt police officers investigate the brutal murder of a young girl, tensions come to a head in their small, racially-segregated town.',
//            'label' => 'Wild Is the Wind',
//            'subLabel' => 'Wild Is the Wind',
//            'slug' => Str::slug('Wild Is the Wind'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Drifting Home',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 7.0,
//            'year' => 2022,
//            'description' => 'Sixth-graders Kosuke and Natsume grew up in the same apartment building as childhood friends. During summer break, while playing in the apartment building that is set to be demolished, they find themselves caught in a strange phenomenon. All they can see around them is a vast sea. Will Kosuke and the others make it back to their world? A journey of farewells in summer has just begun.',
//            'label' => 'Drifting Home',
//            'subLabel' => 'Drifting Home',
//            'slug' => Str::slug('Drifting Home'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Hunting Ava Bravo',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 6.8,
//            'year' => 2022,
//            'description' => 'Billionaire sportsman Buddy King unwinds by hunting human captives on his remote mountain estate. But his latest victim, Ava Bravo is no easy target.',
//            'label' => 'Hunting Ava Bravo',
//            'subLabel' => 'Hunting Ava Bravo',
//            'slug' => Str::slug('Hunting Ava Bravo'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => '365 Days: This Day',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 5.9,
//            'year' => 2022,
//            'description' => 'Laura and Massimo are back and hotter than ever. But the reunited couple\'s new beginning is complicated by Massimo’s family ties and a mysterious man who enters Laura’s life to win her heart and trust, at any cost.',
//            'label' => '365 Days: This Day',
//            'subLabel' => '365 Days: This Day',
//            'slug' => Str::slug('365 Days: This Day'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'One Week Friends',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 6.1,
//            'year' => 2022,
//            'description' => 'A new transfer student, Lin Xiangzhi (Zhao Jinmai), who is quiet and intelligent but always alone, does not make friends with the other students. However, she attracts the attention of Xu Youshu (Lin Yi), a scum of the class. In the process of trying to befriend Lin Xiangzhi, he, the eccentric Song Xiaonan (Shen Yue) and the cool-headed Jiang Wu (Wang Jiahui) discover Lin Xiangzhi\'s secret, that she suffers from a special disease and her memory of her friends is only seven days.',
//            'label' => 'One Week Friends',
//            'subLabel' => 'One Week Friends',
//            'slug' => Str::slug('One Week Friends'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Catch the Fair One',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 7.7,
//            'year' => 2022,
//            'description' => 'A Native American boxer embarks on the fight of her life when she goes in search of her missing sister.',
//            'label' => 'Catch the Fair One',
//            'subLabel' => 'Catch the Fair One',
//            'slug' => Str::slug('Catch the Fair One'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'The Grandmother',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 6.6,
//            'year' => 2022,
//            'description' => 'Susana leaves her life in Paris, where she works as a model, and returns to Madrid to take care of her grandmother Pilar.',
//            'label' => 'The Grandmother',
//            'subLabel' => 'The Grandmother',
//            'slug' => Str::slug('The Grandmother'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Interstellar',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 8.3,
//            'year' => 2014,
//            'description' => 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
//            'label' => 'Interstellar',
//            'subLabel' => 'Interstellar',
//            'slug' => Str::slug('Interstellar'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//        DB::table('tbl_poster')->insert([
//            'title' => 'Three Steps Above Heaven',
//            'duration' => '120',
//            'type' => 'video',
//            'rating' => 0,
//            'views' => 0,
//            'imdb' => 7.7,
//            'year' => 2010,
//            'description' => 'Story of two young people who belong to different worlds. It is the chronicle of a love improbable, almost impossible but inevitable dragging in a frantic journey they discover the first great love. Babi is a girl from upper-middle class that is educated in goodness and innocence . Hache is a rebellious boy, impulsive, unconscious, has a appetite for risk and danger embodied in endless fights and illegal motorbike races, the limit of common sense',
//            'label' => 'Three Steps Above Heaven',
//            'subLabel' => 'Three Steps Above Heaven',
//            'slug' => Str::slug('Three Steps Above Heaven'),
//            'comment' => 0,
//            'enable' => 1,
//        ]);
//
            for ($i = 21; $i <= 46; $i++){
                for ($j = 0; $j <= 3; $j++){
                    DB::table('tbl_poster_genres')->insert([
                        'poster_id' => $i,
                        'genre_id' => rand(2, 4) + $j,
                    ]);
                }
            }
    }
}
